### ISSUE TITLE
Error: destination is invalid

### ISSUE THREAD

**Issue by adarshaJha** [sachushaji/StellarToken#1]
Error: destination is invalid
    at Function.payment (/home/adarsh.jha/Documents/StellarToken/_WebApp/node_modules/stellar-base/lib/operations/payment.js:31:11)
    at /home/adarsh.jha/Documents/StellarToken/_WebApp/utils/xlmtransfer.js:41:42
    at process._tickCallback (internal/process/next_tick.js:68:7)

**Comment by sachushaji** [comment]
Can you give more info on the issue?

**Comment by sachushaji** [comment]
Closing issue as there is no activity.
